// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	model "pg/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// AddCard provides a mock function with given fields: ctx, _a1
func (_m *Repository) AddCard(ctx context.Context, _a1 model.Card) (model.Card, error) {
	ret := _m.Called(ctx, _a1)

	var r0 model.Card
	if rf, ok := ret.Get(0).(func(context.Context, model.Card) model.Card); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(model.Card)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Card) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCard provides a mock function with given fields: ctx, cardID
func (_m *Repository) DeleteCard(ctx context.Context, cardID int64) error {
	ret := _m.Called(ctx, cardID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, cardID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCardByID provides a mock function with given fields: ctx, cardID
func (_m *Repository) GetCardByID(ctx context.Context, cardID int64) (model.Card, error) {
	ret := _m.Called(ctx, cardID)

	var r0 model.Card
	if rf, ok := ret.Get(0).(func(context.Context, int64) model.Card); ok {
		r0 = rf(ctx, cardID)
	} else {
		r0 = ret.Get(0).(model.Card)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, cardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCardByNumber provides a mock function with given fields: ctx, number
func (_m *Repository) GetCardByNumber(ctx context.Context, number string) (model.Card, error) {
	ret := _m.Called(ctx, number)

	var r0 model.Card
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Card); ok {
		r0 = rf(ctx, number)
	} else {
		r0 = ret.Get(0).(model.Card)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCards provides a mock function with given fields: ctx, limit, lastID
func (_m *Repository) GetCards(ctx context.Context, limit int, lastID int64) ([]model.Card, error) {
	ret := _m.Called(ctx, limit, lastID)

	var r0 []model.Card
	if rf, ok := ret.Get(0).(func(context.Context, int, int64) []model.Card); ok {
		r0 = rf(ctx, limit, lastID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Card)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int64) error); ok {
		r1 = rf(ctx, limit, lastID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCard provides a mock function with given fields: ctx, _a1
func (_m *Repository) UpdateCard(ctx context.Context, _a1 model.Card) (model.Card, error) {
	ret := _m.Called(ctx, _a1)

	var r0 model.Card
	if rf, ok := ret.Get(0).(func(context.Context, model.Card) model.Card); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(model.Card)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Card) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
